version: "1"
rules:
  - base: luci
    upstream: pexcn:luci    # change `wei` to the owner of upstream repo
    mergeMethod: merge
  - base: master
    upstream: pexcn:master    # change `wei` to the owner of upstream repo
    mergeMethod: merge
